apiVersion: apps/v1
kind: Deployment
metadata:
  name: vio
  labels:
    k8s-app: vio
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: vio
  template:
    metadata: 
      labels:
        k8s-app: vio
    spec:
      containers:
      - name: vio-pod
        image: nvidia/cuda:12.1.0-cudnn8-devel-ubuntu20.04
        command: ["sleep", "infinity"]
        volumeMounts:
          - mountPath: /root/dataset
            name: vio-data-ivannia
        resources:
          limits:
            nvidia.com/gpu: "1"
            memory: "64G"
            cpu: "1"
          requests:
             memory: "64G"
             cpu: "1"
      volumes:
        - name: vio-data-ivannia
          persistentVolumeClaim:
            claimName: vio-data-ivannia
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-A10
                #- Tesla-V100-SXM2-32GB